set -g destroy-unattached off
set -g focus-events on
set -g history-limit 50000
set -g mouse on
set -g set-clipboard on
set -g window-size latest
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"
